services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: supercandidate
      POSTGRES_PASSWORD: ultrasecretpassword
      POSTGRES_DB: takehometestDB
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
